# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 05:33
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
                ('stop_date', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
                ('role_of_abuser', models.IntegerField()),
                ('reported_date', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
                ('family_context', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.IntegerField()),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth (yyyy-mm-dd)')),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('number_of_abuses', models.IntegerField(blank=True, default=None, null=True)),
                ('services_required', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
        migrations.CreateModel(
            name='Client_Current_Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication1', models.CharField(max_length=50)),
                ('purpose1', models.CharField(max_length=150)),
                ('medication2', models.CharField(max_length=50)),
                ('purpose2', models.CharField(max_length=150)),
                ('sexual_orientation', models.IntegerField()),
                ('income', models.IntegerField()),
                ('level_of_education', models.IntegerField()),
                ('profession', models.CharField(max_length=50)),
                ('in_treatment', models.BooleanField()),
                ('abuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Abuse')),
            ],
        ),
        migrations.CreateModel(
            name='InviteKey',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='abuse',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Client'),
        ),
    ]
