# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-05 02:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferredBy',
            fields=[
                ('web', models.BooleanField(default=False)),
                ('social_service', models.BooleanField(default=False)),
                ('health_practitioner', models.BooleanField(default=False)),
                ('alcoholics_anonymous', models.BooleanField(default=False)),
                ('drug_treatment_group', models.BooleanField(default=False)),
                ('advertisement', models.BooleanField(default=False)),
                ('other2', models.CharField(blank=True, max_length=30)),
                ('client1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stats.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesRequested',
            fields=[
                ('victim_services', models.IntegerField()),
                ('individual_therapy', models.IntegerField()),
                ('group_therapy', models.IntegerField()),
                ('client1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stats.Client')),
            ],
        ),
        migrations.AlterField(
            model_name='abuse',
            name='family_context',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='abuse',
            name='reported_date',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='abuse',
            name='start_date',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='abuse',
            name='stop_date',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='services_required',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
