# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-05 02:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20170405_0202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='services_required',
        ),
    ]
