# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-16 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20170612_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abuse',
            name='family_context',
            field=models.CharField(blank=True, max_length=12, verbose_name='Family Context'),
        ),
        migrations.AlterField(
            model_name='abuse',
            name='reported_date',
            field=models.CharField(blank=True, max_length=4, verbose_name='Reported Date (Year)'),
        ),
        migrations.AlterField(
            model_name='abuse',
            name='role_of_abuser',
            field=models.IntegerField(blank=True, null=True, verbose_name='Role of Abuser'),
        ),
        migrations.AlterField(
            model_name='abuse',
            name='start_date',
            field=models.CharField(blank=True, max_length=4, verbose_name='Start Date (Year)'),
        ),
        migrations.AlterField(
            model_name='abuse',
            name='stop_date',
            field=models.CharField(blank=True, max_length=4, verbose_name='Start Date (Year)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_number',
            field=models.IntegerField(verbose_name='Client Number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='number_of_abuses',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Number of Abuses'),
        ),
        migrations.AlterField(
            model_name='currentsituation',
            name='abuse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Abuse', verbose_name='Abuse ID'),
        ),
        migrations.AlterField(
            model_name='currentsituation',
            name='in_treatment',
            field=models.BooleanField(verbose_name='In Treatment?'),
        ),
        migrations.AlterField(
            model_name='currentsituation',
            name='income',
            field=models.IntegerField(blank=True, null=True, verbose_name='Income'),
        ),
        migrations.AlterField(
            model_name='currentsituation',
            name='level_of_education',
            field=models.IntegerField(blank=True, null=True, verbose_name='Level of Education'),
        ),
        migrations.AlterField(
            model_name='currentsituation',
            name='medication1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Medication 1'),
        ),
        migrations.AlterField(
            model_name='currentsituation',
            name='medication2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Medication 2'),
        ),
        migrations.AlterField(
            model_name='currentsituation',
            name='profession',
            field=models.CharField(blank=True, max_length=50, verbose_name='Profession'),
        ),
        migrations.AlterField(
            model_name='currentsituation',
            name='purpose1',
            field=models.CharField(blank=True, max_length=150, verbose_name='Purpose of 1st Med.'),
        ),
        migrations.AlterField(
            model_name='currentsituation',
            name='purpose2',
            field=models.CharField(blank=True, max_length=150, verbose_name='Purpose of 2nd Med.'),
        ),
        migrations.AlterField(
            model_name='currentsituation',
            name='sexual_orientation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sexual Orientation'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='advertisement',
            field=models.BooleanField(default=False, verbose_name='Advertisement'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='alcoholics_anonymous',
            field=models.BooleanField(default=False, verbose_name='Alcoholics Anonymous'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='drug_treatment_group',
            field=models.BooleanField(default=False, verbose_name='Drug Treatment Group'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='health_practitioner',
            field=models.BooleanField(default=False, verbose_name='Health Practitioner'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='other',
            field=models.CharField(blank=True, max_length=30, verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='social_service',
            field=models.BooleanField(default=False, verbose_name='Social Service'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='web',
            field=models.BooleanField(default=False, verbose_name='Web'),
        ),
        migrations.AlterField(
            model_name='requestedservice',
            name='group_therapy',
            field=models.IntegerField(blank=True, null=True, verbose_name='Group Therapy'),
        ),
        migrations.AlterField(
            model_name='requestedservice',
            name='individual_therapy',
            field=models.BooleanField(verbose_name='Individual Therapy'),
        ),
        migrations.AlterField(
            model_name='requestedservice',
            name='victim_services',
            field=models.BooleanField(verbose_name='Victim Services'),
        ),
    ]
