# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-18 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_auto_20170716_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_number',
            field=models.IntegerField(unique=True, verbose_name='Client Number'),
        ),
        migrations.AlterField(
            model_name='currentsituation',
            name='sexual_orientation',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Sexual Orientation'),
            preserve_default=False,
        ),
    ]
