# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 02:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stats', '0007_auto_20170718_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='abuse',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Client', verbose_name='Associated Client Number'),
        ),
        migrations.AlterField(
            model_name='currentsituation',
            name='abuse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Abuse', verbose_name='Associated Client ID'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stats.Client', verbose_name='Associated Client Number'),
        ),
        migrations.AlterField(
            model_name='requestedservice',
            name='client1',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stats.Client', verbose_name='Associated Client Number'),
        ),
    ]
