# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 03:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_auto_20170728_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abuse',
            name='role_of_abuser',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Role of Abuser'),
        ),
        migrations.AlterField(
            model_name='abuse',
            name='stop_date',
            field=models.CharField(blank=True, max_length=4, verbose_name='Stop Date (Year)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Age at time of visit'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Input by User'),
        ),
        migrations.AlterField(
            model_name='currentsituation',
            name='abuse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Abuse', verbose_name='Associated Client Number'),
        ),
        migrations.AlterField(
            model_name='currentsituation',
            name='income',
            field=models.CharField(blank=True, choices=[('Less than $20,000', 'Less than $20,000'), ('$20,000 - $34,999', '$20,000 - $34,999'), ('$35,000 - $49,999', '$35,000 - $49,999'), ('$50,000 - $75,999', '$50,000 - $75,999'), ('$75,000 - $99,999', '$75,000 - $99,999'), ('$100,000 - $149,999', '$100,000 - $149,999'), ('$150,000 - $199,999', '$150,000 - $199,999'), ('$200,000 or more', '$200,000 or more')], default=django.utils.timezone.now, max_length=50, verbose_name='Income'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currentsituation',
            name='level_of_education',
            field=models.CharField(blank=True, choices=[('Secondary education or less', 'Secondary education or less'), ('Diploma Program', 'Diploma Program'), ('Post-graduate - Bachelors', 'Post-graduate - Bachelors'), ('Post-graduate - Graduate', 'Post-graduate - Graduate'), ('Post-graduate - Professional', 'Post-graduate - Professional'), ('Post-graduate - Doctorate', 'Post-graduate - Doctorate')], default=django.utils.timezone.now, max_length=50, verbose_name='Level of Education'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currentsituation',
            name='sexual_orientation',
            field=models.CharField(blank=True, choices=[('Heterosexual', 'Heterosexual'), ('Homosexual', 'Homosexual'), ('Bisexual', 'Bisexual'), ('Transexual', 'Transexual'), ('Other', 'Other')], max_length=10, verbose_name='Sexual Orientation'),
        ),
        migrations.AlterField(
            model_name='requestedservice',
            name='group_therapy',
            field=models.BooleanField(default=False, verbose_name='Group Therapy'),
            preserve_default=False,
        ),
    ]
