# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_auto_20170803_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentsituation',
            name='income',
            field=models.CharField(blank=True, choices=[('Less than $20,000', 'Less than $20,000'), ('$20,000 - $34,999', '$20,000 - $34,999'), ('$35,000 - $49,999', '$35,000 - $49,999'), ('$50,000 - $75,999', '$50,000 - $75,999'), ('$75,000 - $99,999', '$75,000 - $99,999'), ('$100,000 - $149,999', '$100,000 - $149,999'), ('$150,000 - $199,999', '$150,000 - $199,999'), ('$200,000 or more', '$200,000 or more')], max_length=50, null=True, verbose_name='Income'),
        ),
        migrations.AlterField(
            model_name='currentsituation',
            name='level_of_education',
            field=models.CharField(blank=True, choices=[('Secondary education or less', 'Secondary education or less'), ('Diploma Program', 'Diploma Program'), ('Post-graduate - Bachelors', 'Post-graduate - Bachelors'), ('Post-graduate - Graduate', 'Post-graduate - Graduate'), ('Post-graduate - Professional', 'Post-graduate - Professional'), ('Post-graduate - Doctorate', 'Post-graduate - Doctorate')], max_length=50, null=True, verbose_name='Level of Education'),
        ),
        migrations.AlterField(
            model_name='currentsituation',
            name='sexual_orientation',
            field=models.CharField(blank=True, choices=[('Heterosexual', 'Heterosexual'), ('Homosexual', 'Homosexual'), ('Bisexual', 'Bisexual'), ('Transexual', 'Transexual'), ('Other', 'Other')], max_length=10, null=True, verbose_name='Sexual Orientation'),
        ),
    ]
