# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-14 05:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
                ('stop_date', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
                ('role_of_abuser', models.IntegerField()),
                ('reported_date', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
                ('family_context', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.IntegerField()),
                ('date_of_birth', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
                ('age', models.IntegerField()),
                ('number_of_abuses', models.IntegerField()),
                ('services_required', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
        migrations.CreateModel(
            name='Client_Current_Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication1', models.CharField(max_length=50)),
                ('purpose1', models.CharField(max_length=150)),
                ('medication2', models.CharField(max_length=50)),
                ('purpose2', models.CharField(max_length=150)),
                ('sexual_orientation', models.IntegerField()),
                ('income', models.IntegerField()),
                ('level_of_education', models.IntegerField()),
                ('profession', models.CharField(max_length=50)),
                ('in_treatment', models.BooleanField()),
                ('abuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Abuse')),
            ],
        ),
        migrations.AddField(
            model_name='abuse',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.Client'),
        ),
    ]
