# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20170302_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitekey',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
