# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_remove_client_services_required'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReferredBy',
            new_name='Referral',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='client1',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='referral',
            old_name='other2',
            new_name='other',
        ),
    ]
