# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20170306_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='number_of_abuses',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
