# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20170301_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
