# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20170525_0542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client_Current_Situation',
            new_name='CurrentSituation',
        ),
        migrations.RenameModel(
            old_name='ServicesRequested',
            new_name='RequestedService',
        ),
    ]
