# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20170306_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.IntegerField(),
        ),
    ]
